substitutions:
  devicename: garage_opener

packages:
  common: !include .common.yaml
  
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
  - platform: dht
    pin: D7
    temperature:
      name: "Garage Temperature"
      unit_of_measurement: "°C"
    humidity:
      name: "Garage Humidity"
    update_interval: 120s

binary_sensor:
  - platform: gpio
    name: "Garage Door"
    device_class: "garage_door"
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: true

switch:
  - platform: gpio
    pin: D2
    id: relay
  - platform: template
    name: "Garage Remote"
    icon: "mdi:garage"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 200ms
    - switch.turn_off: relay
    
  - platform: restart 
    name: "Garage Remote Restart"
