esphome:
  name: wellv2
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Well Fallback Hotspot"
    password: "XP3ipKcUzXmJ"
captive_portal:
logger:
api:
ota:
status_led:
  pin:
    number: D0
    inverted: True
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    mac_address:
      name: ESP Mac Wifi Address
binary_sensor:
  - platform: status
    name: "Well Sensor Status"

  # Well Pump on/off
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
      inverted: True
    id: well_pump
    name: "Well Pump"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

i2c:
  scl: D1
  sda: D2
  scan: True
ads1115:
  - address: 0x48
    continuous_mode: on
sensor:
  - platform: wifi_signal
    id: well_wifi_signal
    name: "Well Sensor WiFi Signal"
    update_interval: 120s

  # Water Pressure Sensor 0-80psi
  - platform: ads1115
    multiplexer: 'A0_A1'
    gain: 6.144
    name: "Well Water Pressure"
    id: well_water_pressure
    update_interval: 20s
    unit_of_measurement: "psi"
    icon: "mdi:gauge"
    accuracy_decimals: 1
    filters:
      - median:
          window_size: 9 
          send_every: 3
      - lambda: |-
          if(x < 0) { return 0; } else { return x; };
      - calibrate_polynomial:
          degree: 2
          datapoints:
            - 1.120 -> 0.0  
            #- 0.200 -> 10.0
            #- 1.310 -> 15.0
            #- 0.920 -> 20.0
            #- 1.061 -> 25.0
            #- 1.178 -> 30.0
            #- 0.780 -> 35.0
            - 2.500 -> 40.0
            #- 1.501 -> 45.0
            #- 0.900 -> 50.0
            #- 1.000 -> 55.0
            #- 1.859 -> 60.0
            #- 1.977 -> 65.0
            #- 2.097 -> 70.0
            #- 2.209 -> 75.0
            - 4.800 -> 80.0
      - lambda: |-
          if(x < 0) { return 0; } else { return x; };

