esphome:
  name: well
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Well Fallback Hotspot"
    password: "XP3ipKcUzXmJ"

captive_portal:
logger:
api:
ota:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    mac_address:
      name: ESP Mac Wifi Address

status_led:
  pin:
    number: D0
    inverted: True

# Well Pump on/off
binary_sensor:
  - platform: status
    name: "Well Sensor Status"

  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    id: well_pump
    name: "Well Pump"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

# Water Pressure Sensor 0-80psi
# 0-5V through a voltage divider down to 0-3.3V
sensor:
  - platform: wifi_signal
    id: well_wifi_signal
    name: "Well Sensor WiFi Signal"
    update_interval: 120s

  - platform: adc
    pin: A0
    id: well_water_pressure
    name: "Well Water Pressure"
    update_interval: 10s
    unit_of_measurement: "psi"
    icon: "mdi:gauge"
    accuracy_decimals: 0
    filters:
      - max:
          window_size: 12
          send_every: 6
      - lambda: |-
          if(x < 0) { return 0; } else { return x; };
      - calibrate_polynomial:
          degree: 3
          datapoints:
            - 0.000 -> 0.0  
            - 0.200 -> 10.0
            # - 0.824 -> 15.0
            # - 0.920 -> 20.0
            # - 1.061 -> 25.0
            # - 1.178 -> 30.0
            - 0.780 -> 35.0
            - 0.810 -> 40.0
            # - 1.501 -> 45.0
            - 0.900 -> 50.0
            - 1.000 -> 55.0
            # - 1.859 -> 60.0
            # - 1.977 -> 65.0
            # - 2.097 -> 70.0
            # - 2.209 -> 75.0
            # - 2.900 -> 80.0

